import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Read our privacy policy to understand how we collect, use, and protect your data.",
};

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen flex flex-col bg-white">
      {/* Dark Header for Navbar visibility */}
      <div className="bg-[#0A163B] w-full">
        <Navbar />
      </div>
      
      <div className="flex-1 w-full max-w-4xl mx-auto px-6 py-16 md:py-24">
        <div className="prose prose-blue max-w-none prose-headings:text-[#0A163B] text-[#1A3FA8]">
          <h1 className="text-[#0A163B]">Privacy Policy</h1>
          <p className="text-gray-500">Last updated: April 6, 2026</p>
          
          <p>HolaCXO (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the holacxo.com website (the &quot;Service&quot;).</p>
          
          <p>This page informs you of our policies regarding the collection, use, and disclosure
          of personal data when you use our Service and the choices you have associated
          with that data.</p>
          
          <p>We use your data to provide and improve the Service. By using the Service, you
          agree to the collection and use of information in accordance with this policy.</p>
          
          <h2>Definitions</h2>
          
          <h3>Service</h3>
          <p>Service is the holacxo.com website operated by HolaCXO.</p>
          
          <h3>Personal Data</h3>
          <p>Personal Data means data about a living individual who can be identified from
          those data (or from those and other information either in our possession or likely
          to come into our possession).</p>
          
          <h3>Usage Data</h3>
          <p>Usage Data is data collected automatically, either generated by the use of the
          Service or from the Service infrastructure itself (for example, the duration of a
          page visit).</p>
          
          <h3>Cookies</h3>
          <p>Cookies are small pieces of data stored on your device (computer or mobile
          device).</p>
          
          <h3>Data Controller</h3>
          <p>Data Controller means the natural or legal person who determines the purposes
          for which and the manner in which any personal information is processed. For the
          purpose of this Privacy Policy, HolaCXO is the Data Controller of your Personal
          Data.</p>
          
          <h3>Data Processor (or Service Provider)</h3>
          <p>Data Processor means any natural or legal person who processes data on behalf Privacy Policy1
          of the Data Controller. We may use the services of various Service Providers in
          order to process your data more effectively.</p>
          
          <h3>Data Subject (or User)</h3>
          <p>Data Subject is any living individual who is using our Service and is the subject of
          Personal Data.</p>
          
          <h2>Information We Collect</h2>
          
          <h3>Personal Data</h3>
          <p>While using our Service, we may ask you to provide us with certain personally
          identifiable information that can be used to contact or identify you. This may
          include:</p>
          <ul>
            <li>First name and last name</li>
            <li>Email address</li>
            <li>Company name and job title</li>
            <li>Phone number</li>
          </ul>
          
          <h3>Cookies and Usage Data</h3>
          <p>We may use your Personal Data to contact you with relevant information, updates,
          or content that may be of interest to you based on your engagement with
          HolaCXO. You may opt out of receiving any or all of these communications by
          following the unsubscribe link in any email we send.</p>
          
          <h3>Usage Data</h3>
          <p>We may also collect information on how the Service is accessed and used. This
          Usage Data may include information such as your computer&apos;s Internet Protocol
          IP) address, browser type, browser version, the pages of our Service that you
          visit, the time and date of your visit, the time spent on those pages, and other
          diagnostic data.</p>
          
          <h3>Tracking and Cookies Data</h3>
          <p>We use cookies and similar tracking technologies to track activity on our Service
          and hold certain information. You can instruct your browser to refuse all cookies Privacy Policy2
          or to indicate when a cookie is being sent. However, if you do not accept cookies,
          some portions of our Service may not function as intended.</p>
          
          <p>We use the following types of cookies:</p>
          <ul>
            <li>Session Cookies — to operate our Service</li>
            <li>Preference Cookies — to remember your preferences and settings</li>
            <li>Security Cookies — for security purposes</li>
          </ul>
          
          <h2>How We Use Your Data</h2>
          <p>HolaCXO uses the collected data for the following purposes:</p>
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service</li>
            <li>To provide customer support</li>
            <li>To gather analysis and valuable information to improve our Service</li>
            <li>To monitor usage of our Service</li>
            <li>To detect, prevent, and address technical issues</li>
            <li>To share relevant content, insights, and information about our services with
          you</li>
          </ul>
          
          <h2>Use and Sharing of Mobile Information</h2>
          <p>HolaCXO does not share mobile phone information with any third parties or
          affiliates for marketing or promotional purposes. Any categories of data related to
          text messaging originator opt-in and consent are excluded from sharing practices
          and will not be disclosed to third parties under any circumstances.</p>
          
          <h2>Legal Basis for Processing Personal Data (GDPR)</h2>
          <p>If you are from the European Economic Area EEA, HolaCXO&apos;s legal basis for
          collecting and using the personal information described in this Privacy Policy Privacy Policy3
          depends on the Personal Data we collect and the specific context in which we
          collect it.</p>
          
          <p>HolaCXO may process your Personal Data because:</p>
          <ul>
            <li>We need to perform a contract with you</li>
            <li>You have given us permission to do so</li>
            <li>The processing is in our legitimate interests and is not overridden by your
          rights</li>
            <li>We are required to comply with the law</li>
          </ul>
          
          <h2>Retention of Data</h2>
          <p>HolaCXO will retain your Personal Data only for as long as is necessary for the
          purposes set out in this Privacy Policy. We will retain and use your Personal Data
          to the extent necessary to comply with our legal obligations, resolve disputes, and
          enforce our legal agreements and policies.</p>
          
          <p>Usage Data is generally retained for a shorter period of time, except when this
          data is used to improve the functionality of our Service or we are legally obligated
          to retain it for longer periods.</p>
          
          <h2>Transfer of Data</h2>
          <p>Your information, including Personal Data, may be transferred to and maintained
          on computers located outside of your state, province, country, or other
          governmental jurisdiction where data protection laws may differ from those in your
          jurisdiction.</p>
          
          <p>If you are located outside the United States and choose to provide information to
          us, please note that we transfer the data to the United States and process it there.</p>
          <p>HolaCXO will take all steps reasonably necessary to ensure that your data is
          treated securely and in accordance with this Privacy Policy.</p>
          
          <h2>Disclosure of Data Privacy Policy4</h2>
          <p>HolaCXO may disclose your Personal Data in the good faith belief that such action
          is necessary to:</p>
          <ul>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of HolaCXO</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          
          <h2>Security of Data</h2>
          <p>The security of your data is important to us. While we strive to use commercially
          acceptable means to protect your Personal Data, no method of transmission over
          the Internet or method of electronic storage is 100% secure, and we cannot
          guarantee its absolute security.</p>
          
          <p>No mobile information will be shared with third parties or affiliates for marketing or
          promotional purposes. All other categories exclude text messaging originator opt-
          in data and consent — this information will not be shared with any third parties.</p>
          
          <h2>Your Data Protection Rights (GDPR)</h2>
          <p>If you are a resident of the European Economic Area EEA, you have the following
          data protection rights:</p>
          <ul>
            <li>The right to access — You can request copies of your Personal Data.</li>
            <li>The right to rectification — You have the right to have inaccurate or
          incomplete information corrected.</li>
            <li>The right to erasure — You have the right to request that we delete your
          Personal Data under certain conditions.</li>
            <li>The right to restrict processing — You have the right to request that we
          restrict the processing of your Personal Data.</li>
            <li>The right to data portability — You have the right to request that we transfer
          your data to another organisation or directly to you Privacy Policy5.</li>
            <li>The right to object — You have the right to object to our processing of your
          Personal Data.</li>
            <li>The right to withdraw consent — You have the right to withdraw your consent
          at any time where HolaCXO relied on your consent to process your
          information.</li>
          </ul>
          
          <p>To exercise any of these rights, please contact us. We may ask you to verify your
          identity before responding to such requests. You also have the right to complain to
          a Data Protection Authority about our collection and use of your Personal Data.</p>
          
          <h2>Service Providers</h2>
          <p>We may employ third party companies and individuals to facilitate our Service,
          provide the Service on our behalf, perform Service-related services, or assist us in
          analysing how our Service is used. These third parties have access to your
          Personal Data only to perform these tasks on our behalf and are obligated not to
          disclose or use it for any other purpose.</p>
          
          <h2>Analytics</h2>
          <h3>Google Analytics</h3>
          <p>We use Google Analytics to monitor and analyse use of our Service. Google uses
          the data collected to track and report website traffic. You can opt out of having
          your activity available to Google Analytics by installing the Google Analytics opt-
          out browser add-on at tools.google.com/dlpage/gaoptout. For more information
          on Google&apos;s privacy practices, visit: www.google.com/intl/en/policies/privacy</p>
          
          <h2>Links to Other Sites</h2>
          <p>Our Service may contain links to other sites not operated by us. We strongly
          advise you to review the Privacy Policy of every site you visit. We have no control
          over and assume no responsibility for the content, privacy policies, or practices of
          any third party sites or services.</p>
          
          <h2>Children&apos;s Privacy Privacy Policy6</h2>
          <p>Our Service does not address anyone under the age of 18. We do not knowingly
          collect personally identifiable information from anyone under the age of 18. If you
          are a parent or guardian and believe your child has provided us with Personal
          Data, please contact us and we will take steps to remove that information from our
          systems.</p>
          
          <h2>Changes to This Privacy Policy</h2>
          <p>We may update our Privacy Policy from time to time. We will notify you of any
          changes by posting the new Privacy Policy on this page and updating the effective
          date at the top. You are advised to review this Privacy Policy periodically for any
          changes. Changes become effective when posted on this page.</p>
          
          <h2>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us at:</p>
          <p>Email: tanushka@holacxo.com Website: holacxo.com</p>
        </div>
      </div>
      
      <Footer />
    </main>
  );
}
